[package]
name = "kcmkc"
version = "0.1.0"
authors = ["Matteo Ceccarello <mceccarello@unibz.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kcmkc-base = {path = "../kcmkc-base"}
anyhow = "1.0"
